version: '3.8'
services:
  app:
    build: .
    image: albumcharts:latest
    container_name: albumcharts_app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_KEY=base64:YOUR_APP_KEY_HERE
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    ports:
      - "9000:9000"
    # No depends_on here; web depends on app
  web:
    image: nginx:alpine
    container_name: albumcharts_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
