version: '3.8'

services:
  app:
    build: .
    container_name: albumcharts_app
    restart: unless-stopped
    command: ["php-fpm"]
    volumes:
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
    environment:
      APP_ENV: ${APP_ENV}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: albumcharts_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    image: nginx:1.25
    container_name: albumcharts_web
    restart: unless-stopped
    ports:
      - "8044:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro   # nginx config
      - ./public:/var/www/html/public:ro
      - ./storage:/var/www/html/storage
    depends_on:
      - app

volumes:
  db_data:
