version: '3.8'
services:
  app:
    build: .
    container_name: albumcharts_app
    restart: unless-stopped
    command: ["/bin/sh", "-c", "chmod +x /var/www/html/wait-for-db.sh && /var/www/html/wait-for-db.sh db php artisan migrate --force && php-fpm"]
    volumes:
      - ./wait-for-db.sh:/var/www/html/wait-for-db.sh
      - ./storage:/var/www/html/storage
    environment:
      APP_ENV: ${APP_ENV}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9009:9000"
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: albumcharts_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
