version: '3.8'
services:
  app:
    build: .
  image: albumcharts:latest
  container_name: albumcharts_app
  restart: unless-stopped
  command: /bin/sh -c "php artisan migrate --force && php-fpm"
  environment:
      - APP_ENV=production
      - DB_CONNECTION=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=db
      - DB_USERNAME=db
      - DB_PASSWORD=db
  volumes:
    - ./storage:/var/www/html/storage
  ports:
    - "9000:9000"
  depends_on:
      - db
  web:
    image: nginx:alpine
    container_name: albumcharts_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
  db:
    image: mariadb:11
    container_name: albumcharts_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=albumcharts
      - MYSQL_USER=albumcharts
      - MYSQL_PASSWORD=albumcharts
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data:
